#!/usr/bin/env bash
# One-command production deploy for the TraceBloom demo stack.
#
#   infra/prod/deploy.sh up            # (re)deploy: build/pull, migrate, start
#   infra/prod/deploy.sh seed          # load the demo project (idempotent)
#   infra/prod/deploy.sh reset         # reset demo data to a clean seeded state
#   infra/prod/deploy.sh verify        # post-seed assertions (same as CI smoke)
#   infra/prod/deploy.sh down          # stop the stack (volumes are kept)
#   infra/prod/deploy.sh logs [svc]    # follow logs
#
# First `up` generates an .env with random passwords next to this script.
# Set DEMO_DOMAIN in that .env (a DNS name pointing at this VM) to enable
# automatic HTTPS; leave it empty to serve plain HTTP on :80.
#
# Prerequisites on the VM: docker with the compose plugin, and this repository
# (git clone). Nothing else.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${HERE}/.env"
COMPOSE=(docker compose --env-file "${ENV_FILE}" -f "${HERE}/docker-compose.prod.yml")

random_secret() {
  # 32 hex chars; openssl is present ~everywhere, /dev/urandom is the fallback.
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 16
  else
    head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

ensure_env() {
  if [[ -f "${ENV_FILE}" ]]; then
    return
  fi
  echo "==> No .env found; generating ${ENV_FILE} with random passwords."
  umask 077
  cat >"${ENV_FILE}" <<EOF
# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Keep this file private.
DEMO_DOMAIN=
POSTGRES_PASSWORD=$(random_secret)
CLICKHOUSE_PASSWORD=$(random_secret)
POSTGRES_RO_PASSWORD=$(random_secret)
CLICKHOUSE_RO_PASSWORD=$(random_secret)
EOF
  echo "    Edit DEMO_DOMAIN in ${ENV_FILE} for automatic HTTPS, then re-run."
}

wait_healthy() {
  local container="$1" tries="${2:-60}"
  echo -n "==> Waiting for ${container} to become healthy "
  for _ in $(seq 1 "${tries}"); do
    local status
    status="$(docker inspect --format '{{.State.Health.Status}}' "${container}" 2>/dev/null || echo missing)"
    if [[ "${status}" == "healthy" ]]; then
      echo "— healthy."
      return 0
    fi
    echo -n "."
    sleep 2
  done
  echo
  echo "ERROR: ${container} did not become healthy; recent logs:" >&2
  docker logs --tail 50 "${container}" >&2 || true
  return 1
}

cmd_up() {
  ensure_env
  # Prebuilt images (TRACEBLOOM_IMAGE_PREFIX in .env) are pulled; otherwise
  # everything builds locally on the VM.
  if grep -q '^TRACEBLOOM_IMAGE_PREFIX=..*' "${ENV_FILE}"; then
    echo "==> Pulling prebuilt images"
    "${COMPOSE[@]}" pull
    "${COMPOSE[@]}" up -d
  else
    echo "==> Building images locally (first build takes a few minutes)"
    "${COMPOSE[@]}" up -d --build
  fi
  # `up -d` orders startup via depends_on: databases -> one-shot migrate ->
  # collector/dashboard -> caddy. Migrations therefore have already succeeded
  # once the dashboard reports healthy.
  wait_healthy tracebloom-prod-dashboard
  echo "==> Stack is up."
  echo "    Seed the demo project next:   $0 seed"
  echo "    Nightly demo reset (recommended) — install with:"
  echo "      ( crontab -l 2>/dev/null; echo '17 4 * * * $(realpath "$0") reset' ) | crontab -"
}

demo_cmd() {
  "${COMPOSE[@]}" run --rm demo-seed node apps/demo/dist/main.js "$@"
}

case "${1:-up}" in
  up) cmd_up ;;
  seed) demo_cmd seed ;;
  reset) demo_cmd reset ;;
  verify) demo_cmd verify ;;
  down) "${COMPOSE[@]}" down ;;
  logs) shift; "${COMPOSE[@]}" logs -f "$@" ;;
  *)
    echo "usage: $0 {up|seed|reset|down|logs [service]}" >&2
    exit 2
    ;;
esac
